safe:        false
port:        4000
baseurl:     /
name: Gareth Sweet, Associate Creative Director (Copy)
url: http://garethsweet.com
google-analytics-tracking-id: UA-XXXXXXX-X

source:      .
destination: ./_site
plugins_dir: ./_plugins
exclude: [deploy.sh]

future:      true
lsi:         false
markdown:    kramdown
permalink:   /:categories/:title/

maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

  syntax_highlighter_opts:
    wrap: div
    line_numbers: inline
    line_numbers_start: 1
    tab_width: 4
    bold_every: 10
    css: style
